# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute

app_dashboard:
    path: /
    controller: App\Controller\DefaultController::index

app_rh_dashboard:
    path: /rh
    controller: App\Controller\RHController::dashboard

app_rh_register:
    path: /rh/register
    controller: App\Controller\RHController::register

app_rh_add_user:
    path: /rh/add-user
    controller: App\Controller\RHController::addUser

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

