# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute

app_dashboard:
    path: /
    controller: App\Controller\DefaultController::index

app_rh_dashboard:
    path: /rh
    controller: App\Controller\RHController::dashboard

app_rh_register:
    path: /rh/register
    controller: App\Controller\RHController::register


app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login